---
default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

ci:
  autoupdate_commit_msg: 'pre-commit: autoupdate hooks'
  autofix_prs: false
  # docker is not supported on pre-commit.ci
  skip: [shellcheck]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key

  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.30
    hooks:
      - id: conform
        stages:
          - commit-msg

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: local
    hooks:
      - id: detect-confidential-license
        name: Checks if the file contains "confidential" string
        entry: ./scripts/detect-confidential-license.sh
        language: script
        types: [text]
        exclude: ^(scripts/detect-confidential-license.sh|.pre-commit-config.yaml)$
